== Test the deployment

NOTE: These steps must be executed from a network that has access to the Kubernetes API, as configured by the EKS public access endpoint and Kubernetes API public access CIDR parameters. For more information, see https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html[Installing kubectl^]. If you enabled the optional bastion host, you can connect to it by using SSH. Use the key pair that you specified during deployment and the IP address from the Outputs tab of the AWS CloudFormation stack. The bastion host already has kubectl installed and configured so that it connects to the cluster. To test the CLI, connect to the cluster, and run the following command.

. In the CloudFormation console, choose the Outputs tab and retrieve the URL from the GrafanaURL output.
. Retrieve the password for the grafana ui using the following kubectl command.
```
`kubectl get secret --namespace default grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo`
```
[start=3]
. Navigate to the consule URL retrieved in step 1 and login using `admin` as the user and the passowrd retrieved in step 2.
. Choose *Configuration* and then *Data Sources* and then *Prometheus*. Choosing *Test* on this page should result in the message *Data source is working*.

== Best practices for using {partner-product-short-name} on Amazon EKS

Best practices for various aspects of creating and managing dashboards are available in the https://grafana.com/docs/grafana/latest/best-practices/[Grafana best practices documentation].

== Security

Security considerations for Grafana are available in the https://grafana.com/docs/grafana/latest/administration/security/[Grafana security documentation].

== Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

_Add any other details that will help the customer use the software on AWS._
